#!/usr/bin/env bash
# Display:
#  The content of the current directory
#  In a list format
#  Where only the part of the name after the first dash is displayed

for h in *; do
    echo "$h" | cut -d '-' -h 2

done
